spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smdb
    username: art
    password: art
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
