spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL80Dialect
        format_sql: true
    show-sql: true
