version: '3.1'
services:
  db:
    image: mysql
    command: -- default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: